In [1]:
import torch

In [2]:
X = torch.tensor([[1, 1, -1], [0, -1, 1]], requires_grad=True, dtype=torch.float32)
W1 = torch.tensor([[1, 0], [1, 2]], requires_grad=True, dtype=torch.float32)

A = torch.matmul(W1, X)
A.retain_grad()
W2 = torch.tensor([[1, -2]], requires_grad=True, dtype=torch.float32)

print(A)

B = torch.matmul(W2, A)
B.retain_grad()
Y = torch.tensor([[1, -2 , -1]], requires_grad=True, dtype=torch.float32)

print(B)

E = torch.subtract(Y, B)
print(E)

# Calculate the L2 regularization term
C = torch.sum(torch.square(E))
print(C)



tensor([[ 1.,  1., -1.],
        [ 1., -1.,  1.]], grad_fn=<MmBackward0>)
tensor([[-1.,  3., -3.]], grad_fn=<MmBackward0>)
tensor([[ 2., -5.,  2.]], grad_fn=<SubBackward0>)
tensor(33., grad_fn=<SumBackward0>)


In [3]:
C.backward()

print(W1.grad)
print(W2.grad)
print(X.grad)
print(Y.grad)
print(B.grad)
print(A.grad)

tensor([[ 10., -14.],
        [-20.,  28.]])
tensor([[ 10., -18.]])
tensor([[  4., -10.,   4.],
        [ 16., -40.,  16.]])
tensor([[  4., -10.,   4.]])
tensor([[-4., 10., -4.]])
tensor([[ -4.,  10.,  -4.],
        [  8., -20.,   8.]])


In [13]:
X = torch.stack([torch.ones(4, requires_grad=True, dtype=torch.float32),
                 torch.tensor([1, 2, 3, 4], requires_grad=True, dtype=torch.float32)], 1)
Y = torch.tensor([[2, 3, 3, 5]], requires_grad=True, dtype=torch.float32)

print(X)
print(Y)

# W = torch.matmul(torch.matmul(torch.inverse(torch.matmul(X, X.t())), X.t), Y)
W = (X.T @ X).inverse() @ X.T @ Y.T
print(W)

tensor([[1., 1.],
        [1., 2.],
        [1., 3.],
        [1., 4.]], grad_fn=<StackBackward0>)
tensor([[2., 3., 3., 5.]], requires_grad=True)
tensor([[1.0000],
        [0.9000]], grad_fn=<MmBackward0>)


In [18]:
X1 = torch.tensor([1, 2, 3, 4], requires_grad=True, dtype=torch.float32)
X2 = torch.tensor([1, 3, 4, 3], requires_grad=True, dtype=torch.float32)
X = torch.stack([torch.ones(4, requires_grad=True, dtype=torch.float32),
                 X1, X2], 1)
Y = torch.tensor([[1, 3, 4, 5]], requires_grad=True, dtype=torch.float32).reshape(4,1)

print(X)
print(Y)

# W = torch.matmul(torch.matmul(torch.inverse(torch.matmul(X, X.t())), X.t), Y)
W = (X.T @ X).inverse() @ X.T @ Y
print(W)


tensor([[1., 1., 1.],
        [1., 2., 3.],
        [1., 3., 4.],
        [1., 4., 3.]], grad_fn=<StackBackward0>)
tensor([[1.],
        [3.],
        [4.],
        [5.]], grad_fn=<ViewBackward0>)
tensor([[-0.3043],
        [ 1.0870],
        [ 0.3043]], grad_fn=<MmBackward0>)
